export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const CLEAR_ORDER = "CLEAR_ORDER"


export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"


export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET";



export const ALL_ORDER_DETAILS_REQUEST = "ALL_ORDER_DETAILS_REQUEST";
export const ALL_ORDER_DETAILS_SUCCESS = "ALL_ORDER_DETAILS_SUCCESS";
export const ALL_ORDER_DETAILS_FAIL = "ALL_ORDER_DETAILS_FAIL";
export const ALL_ORDER_DETAILS_RESET = "ALL_ORDER_DETAILS_RESET"


export const ORDER_MY_DETAILS_REQUEST = "ORDER_MY_DETAILS_REQUEST";
export const ORDER_MY_DETAILS_SUCCESS = "ORDER_MY_DETAILS_SUCCESS";
export const ORDER_MY_DETAILS_FAIL = "ORDER_MY_DETAILS_FAIL";